### ISSUE TITLE
runserver crashes right after start: URI template issue in run_with_falcon function

### ISSUE THREAD

**Issue by mfatihdurmus** [zetaops/zengine#43]
(ulakbusenv)ulakbus@ulakbus:~/ulakbus/ulakbus$ python manage.py runserver
/app/ulakbusenv/local/lib/python2.7/site-packages/riak/security.py:45: UserWarning: OpenSSL 1.0.1f 6 Jan 2014 (>= 1.0.1g required), TLS 1.2 support: False
  warnings.warn(msg, UserWarning)
Development server started on http://127.0.0.1:9001. 

Press Ctrl+C to stop

Traceback (most recent call last):
  File "manage.py", line 199, in <module>
    ManagementCommands()
  File "/app/ulakbusenv/local/lib/python2.7/site-packages/pyoko/manage.py", line 196, in __init__
    self.args.command()
  File "/app/ulakbusenv/local/lib/python2.7/site-packages/zengine/management_commands.py", line 126, in run
    self.run_with_falcon()
  File "/app/ulakbusenv/local/lib/python2.7/site-packages/zengine/management_commands.py", line 142, in run_with_falcon
    from zengine.server import app
  File "/app/ulakbusenv/local/lib/python2.7/site-packages/zengine/server.py", line 132, in <module>
    falcon_app.add_route(url, view_connector(view_path))
  File "/app/ulakbusenv/local/lib/python2.7/site-packages/falcon/api.py", line 309, in add_route
    raise ValueError("uri_template must start with '/'")
ValueError: uri_template must start with '/'

**Comment by evrenesat** [comment]
"runserver" komutu varsayılan olarak "falcon" sunucusunu kullanacak şekilde ayarlanmıştı. Yakın zamanda  Tornado ve websocket desteğini ekledik. Bu süreçte falcon desteği kırılmış (orta vadede bu işlevi tekrar düzelteceğiz). Tornado sunucu tipini varsayılan hale getirdim. 

Sistemin arka ucunu denemek için 2 ayrı terminalde aşağıdaki komutları çalıştırmanız yeterli olacaktır. 
./manage.py runserver
./manage.py runworker

Not: Bu ve diğer yönetim komutlarının kabul ettikleri diğer parametreleri görmek için "-h" parametresi verebilirsiniz.
